<a href="index.php"> Index </a> | 
<a href="list_targeta.php"> Llista de targetes </a> | 
<a href="insert_targeta.php"> Targeta </a> |
<a href="list_venta.php"> Llista Vendes </a> |
<a href="insert_venta.php"> Vendes </a>| 
<a href="list_client.php"> Llista Clients </a> |
<a href="insert_client.php"> Clients </a> |
<a href="list_producte-venta.php"> Llista Producte i Ventes </a> |
<a href="insert_producte-venta.php"> Productes i Ventes </a> |
<a href="list_producte.php"> Tots els productes </a> |
<a href="insert_producte.php"> Insertar els productes </a> |
